# Generated by Django 2.2.2 on 2019-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=200, verbose_name='교사번호')),
                ('t_name', models.CharField(max_length=200, verbose_name='교사이름')),
                ('ins_date', models.DateTimeField(verbose_name='설치 일자')),
            ],
        ),
    ]