# Generated by Django 2.2.2 on 2019-06-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeisAssistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('type1', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='구분1')),
                ('type2', models.CharField(max_length=2, verbose_name='구분2')),
                ('type3', models.CharField(max_length=3, verbose_name='구분3')),
                ('content', models.TextField(verbose_name='내용')),
                ('createYMD', models.DateTimeField(auto_now_add=True, verbose_name='데이터생성일자')),
                ('createId', models.CharField(max_length=20, null=True, verbose_name='교사번호')),
            ],
            options={
                'unique_together': {('type1', 'type2', 'type3')},
            },
        ),
        migrations.CreateModel(
            name='StdRecord',
            fields=[
                ('createYMD', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='데이터생성일자')),
                ('viewLv', models.CharField(default='A', max_length=1, verbose_name='보안레벨')),
                ('content', models.TextField(verbose_name='내용')),
                ('readChk', models.BooleanField(default=False, verbose_name='확인')),
                ('updateYMD', models.DateTimeField(auto_now=True, verbose_name='데이터수정일자')),
                ('recodeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeisAssistant.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='학생id')),
                ('gradeNo', models.CharField(max_length=2, verbose_name='학년')),
                ('classNo', models.CharField(max_length=2, verbose_name='반')),
                ('stdNo', models.CharField(max_length=2, verbose_name='번호')),
                ('stdName', models.CharField(max_length=10, verbose_name='이름')),
                ('stdBirth', models.CharField(max_length=6, verbose_name='생년월일')),
                ('createYMD', models.DateTimeField(auto_now_add=True, verbose_name='데이터생성일자')),
                ('updateYMD', models.DateTimeField(auto_now=True, null=True, verbose_name='데이터수정일자')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='교사번호')),
                ('tName', models.CharField(max_length=20, verbose_name='교사이름')),
                ('tPwd', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('authority', models.CharField(default='00', max_length=2, verbose_name='권한')),
                ('gradeNo', models.CharField(max_length=2, null=True, verbose_name='학년')),
                ('classNo', models.CharField(max_length=2, null=True, verbose_name='반')),
                ('createYMD', models.DateTimeField(auto_now_add=True, verbose_name='데이터생성일자')),
                ('updateYMD', models.DateTimeField(auto_now=True, null=True, verbose_name='데이터수정일자')),
                ('createId', models.CharField(max_length=20, null=True, verbose_name='교사번호')),
                ('updateId', models.CharField(max_length=20, null=True, verbose_name='교사번호')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='stdrecord',
            name='stdid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeisAssistant.Student'),
        ),
        migrations.AddField(
            model_name='stdrecord',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeisAssistant.Teachers'),
        ),
        migrations.AlterUniqueTogether(
            name='stdrecord',
            unique_together={('stdid', 'createYMD', 'tid')},
        ),
    ]
